; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -verify-machineinstrs --riscv-no-aliases < %s \
; RUN:   | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+c -verify-machineinstrs --riscv-no-aliases < %s \
; RUN:   | FileCheck --check-prefix=CHECK-C %s

; The generated BLT does not have a large enough immediate field to encode the
; branch offset. BranchRelaxation will relax this to a BGE + unconditional
; branch to allow this offset to be encoded.
;
; This test ensures that a PseudoJUMP is used for the unconditional branch
; instead of PseudoBR when the C extension is enabled. When the C extension is
; enabled, `jal zero, .LBB0_2` is unconditionally compressed to `c.j .LBB0_2`
; whose immediate field is too small to encode an offset of 4096.
define void @relax_blt(i64 %val) {
; CHECK-LABEL: relax_blt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a1, zero, 255
; CHECK-NEXT:    bge a1, a0, .LBB0_1
; CHECK-NEXT:    jal zero, .LBB0_2
; CHECK-NEXT:  .LBB0_1: # %iftrue
; CHECK-NEXT:    #APP
; CHECK-NEXT:    .zero 4096
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:  .LBB0_2: # %tail
; CHECK-NEXT:    jalr zero, 0(ra)
;
; CHECK-C-LABEL: relax_blt:
; CHECK-C:       # %bb.0:
; CHECK-C-NEXT:    addi a1, zero, 255
; CHECK-C-NEXT:    bge a1, a0, .LBB0_1
; CHECK-C-NEXT:  # %bb.3:
; CHECK-C-NEXT:    jump .LBB0_2, a0
; CHECK-C-NEXT:  .LBB0_1: # %iftrue
; CHECK-C-NEXT:    #APP
; CHECK-C-NEXT:    .zero 4096
; CHECK-C-NEXT:    #NO_APP
; CHECK-C-NEXT:  .LBB0_2: # %tail
; CHECK-C-NEXT:    c.jr ra
  %cmp = icmp slt i64 %val, 256
  br i1 %cmp, label %iftrue, label %tail

iftrue:
  call void asm sideeffect ".space 4096", ""()
  br label %tail

tail:
  ret void
}
